Add exclude glob option in wget job
hysds/lightweight-jobs pull request #10
Opened 2019-09-10 16:02 UTC by shitong01

Similar to: https://github.com/earthobservatory/lightweight-jobs/pull/2

------------------------

Added a field for user to define an exclude glob to exclude files for download.
(kinda like rsync but still different)
From now users can define:
`include_glob`  and `exclude_glob` 
^ both are comma-separated list of globs(wildcards) to include and exclude files. 
Sequence:
1.) Job will create a list of files in `include_glob` first. 
2.) From the list of files in (1), job will remove files that matches `exclude_glob`

[Test logs](https://gist.github.com/shitong01/85193f64ee161af1c0785c1859f3a57c)

2019-09-10 16:03 UTC, shitong01 commented
@pymonger

2019-09-11 16:28 UTC, pymonger requested changes
Hi @shitong01. Looks good. I was wondering though if you could create unit tests for the new functionality under a directory called test? Our unit tests throughout hysds core repos has been sparse but lately as new functionality is added we've asked developers to start including unit tests. We're using the pytest framework. If you need an example, take a look at the unit tests under https://github.com/hysds/hysds_commons under the tests directory. We're setting up CI/CD on CircleCI for the HySDS core packages and so the unit tests will run as part of a pull request creation, e.g. https://github.com/hysds/hysds_commons/blob/develop/.circleci/config.yml.

2019-09-12 02:29 UTC, shitong01 commented
Hi Gerald, sure! Thanks for suggesting that. Will take a look and create a unit test for this!

2019-09-26 14:47 UTC, pymonger approved these changes
@shitong01 i will merge this in so we can get this into the next core release.

2019-09-26 14:47 UTC, merged